# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateKM_rcpp_not_used <- function(t, d, w = as.numeric( c()), strata = as.integer( c()), error = "greenwood") {
    .Call('_km_curve_calculateKM_rcpp_not_used', PACKAGE = 'km.curve', t, d, w, strata, error)
}

